use_frameworks!

platform :ios, '8.0'

target 'CSXNavigationBar_Example' do
  pod 'CSXNavigationBar', :path => '../'
  pod 'Masonry'

  target 'CSXNavigationBar_Tests' do
    inherit! :search_paths

    
  end
end
